FROM node:14.15-alpine
WORKDIR /opt/app
ADD package.json package.json
RUN npm install
ADD . .

ARG FB_APIKEY
ENV FB_APIKEY ${FB_APIKEY}

ARG FB_AUTHDOMAIN
ENV FB_AUTHDOMAIN ${FB_AUTHDOMAIN}

ARG FB_PROJECTID
ENV FB_PROJECTID ${FB_PROJECTID}

ARG FB_STORAGEBUCKET
ENV FB_STORAGEBUCKET ${FB_STORAGEBUCKET}

ARG FB_SENDERID
ENV FB_SENDERID ${FB_SENDERID}

ARG FB_APPID
ENV FB_APPID ${FB_APPID}

ARG FB_MEASUREMENTID
ENV FB_MEASUREMENTID ${FB_MEASUREMENTID}

ARG PRIVATE_KEY_ID
ENV PRIVATE_KEY_ID ${PRIVATE_KEY_ID}

ARG PRIVATE_KEY
ENV PRIVATE_KEY ${PRIVATE_KEY}

RUN npm run build
RUN npm prune --production

CMD ["npm", "start"]
