version: '3'
services:
  top.api:
    image: animeover
    container_name: animeover
    restart: always
    environment:
        FB_APIKEY: ${FB_APIKEY}
        FB_AUTHDOMAIN: ${FB_AUTHDOMAIN}
        FB_PROJECTID: ${FB_PROJECTID}
        FB_STORAGEBUCKET: ${FB_STORAGEBUCKET}
        FB_SENDERID: ${FB_SENDERID}
        FB_APPID: ${FB_APPID}
        FB_MEASUREMENTID: ${FB_MEASUREMENTID}
        PRIVATE_KEY_ID: ${PRIVATE_KEY_ID}
        PRIVATE_KEY: ${PRIVATE_KEY}
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env